---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: demo-project
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  BACKEND_SECRET: 
  K8S_SA_TOKEN: 
  GITHUB_TOKEN: 
  ARGOCD_USERNAME: admin
  ARGOCD_PASSWORD: 