---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-plugins-rhdh
  namespace: demo-project
  labels:
    rhdh.redhat.com/ext-config-sync: "true"
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: './dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic'
        disabled: false
      - package: './dynamic-plugins/dist/backstage-community-plugin-topology'
        disabled: false
      - package: './dynamic-plugins/dist/backstage-plugin-kubernetes'
        disabled: false
      - package: './dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic'
        disabled: false
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-argocd-backend:bs_1.45.3__1.0.2
        disabled: false
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-argocd@sha256:644eb3120c9f0389743f539055253fcf9583fa145dac5975b701ea4635a91788
        disabled: false
...
